#远程正式环境,如打包部署的话是用这个环境

server:
  port: 10001
---
config:
  fileUrl: "xxxxx111"
  current-path: "files"
  currentp-ath1: "files"
  # 日志配置
  log:
    enabled: true              # 是否启用日志输出
    console-output: true       # 是否输出到控制台
    file-output: true          # 是否保存到文件
    flush-interval-seconds: 2   # 每隔多少秒保存一次
    batch-size: 50             # 超过多少条保存一次
    keep-files: 30              # 每个级别/年/月目录下保留最新的文件数量（按日期排序）
    levels:                     # 控制各个日志级别的启用状态
      info: true                # INFO级别是否启用
      error: true               # ERROR级别是否启用
      debug: true               # DEBUG级别是否启用
      warn: true                # WARN级别是否启用
      severe: true              # SEVERE级别是否启用
      dao: true                 # 数据库保存是否启用
---